/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsUuidRouteImport } from './routes/tools/uuid'
import { Route as ToolsUrlCodecRouteImport } from './routes/tools/url-codec'
import { Route as ToolsTimestampRouteImport } from './routes/tools/timestamp'
import { Route as ToolsRegexRouteImport } from './routes/tools/regex'
import { Route as ToolsRedactRouteImport } from './routes/tools/redact'
import { Route as ToolsMockDataRouteImport } from './routes/tools/mock-data'
import { Route as ToolsJsonRouteImport } from './routes/tools/json'
import { Route as ToolsHashRouteImport } from './routes/tools/hash'
import { Route as ToolsCronRouteImport } from './routes/tools/cron'
import { Route as ToolsColorRouteImport } from './routes/tools/color'
import { Route as ToolsCaseRouteImport } from './routes/tools/case'
import { Route as ToolsBeverageRouteImport } from './routes/tools/beverage'
import { Route as ToolsBase64RouteImport } from './routes/tools/base64'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUuidRoute = ToolsUuidRouteImport.update({
  id: '/tools/uuid',
  path: '/tools/uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUrlCodecRoute = ToolsUrlCodecRouteImport.update({
  id: '/tools/url-codec',
  path: '/tools/url-codec',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTimestampRoute = ToolsTimestampRouteImport.update({
  id: '/tools/timestamp',
  path: '/tools/timestamp',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRegexRoute = ToolsRegexRouteImport.update({
  id: '/tools/regex',
  path: '/tools/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRedactRoute = ToolsRedactRouteImport.update({
  id: '/tools/redact',
  path: '/tools/redact',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMockDataRoute = ToolsMockDataRouteImport.update({
  id: '/tools/mock-data',
  path: '/tools/mock-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonRoute = ToolsJsonRouteImport.update({
  id: '/tools/json',
  path: '/tools/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHashRoute = ToolsHashRouteImport.update({
  id: '/tools/hash',
  path: '/tools/hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCronRoute = ToolsCronRouteImport.update({
  id: '/tools/cron',
  path: '/tools/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorRoute = ToolsColorRouteImport.update({
  id: '/tools/color',
  path: '/tools/color',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCaseRoute = ToolsCaseRouteImport.update({
  id: '/tools/case',
  path: '/tools/case',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBeverageRoute = ToolsBeverageRouteImport.update({
  id: '/tools/beverage',
  path: '/tools/beverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/tools/base64',
  path: '/tools/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/beverage': typeof ToolsBeverageRoute
  '/tools/case': typeof ToolsCaseRoute
  '/tools/color': typeof ToolsColorRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/json': typeof ToolsJsonRoute
  '/tools/mock-data': typeof ToolsMockDataRoute
  '/tools/redact': typeof ToolsRedactRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/timestamp': typeof ToolsTimestampRoute
  '/tools/url-codec': typeof ToolsUrlCodecRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/beverage': typeof ToolsBeverageRoute
  '/tools/case': typeof ToolsCaseRoute
  '/tools/color': typeof ToolsColorRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/json': typeof ToolsJsonRoute
  '/tools/mock-data': typeof ToolsMockDataRoute
  '/tools/redact': typeof ToolsRedactRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/timestamp': typeof ToolsTimestampRoute
  '/tools/url-codec': typeof ToolsUrlCodecRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/beverage': typeof ToolsBeverageRoute
  '/tools/case': typeof ToolsCaseRoute
  '/tools/color': typeof ToolsColorRoute
  '/tools/cron': typeof ToolsCronRoute
  '/tools/hash': typeof ToolsHashRoute
  '/tools/json': typeof ToolsJsonRoute
  '/tools/mock-data': typeof ToolsMockDataRoute
  '/tools/redact': typeof ToolsRedactRoute
  '/tools/regex': typeof ToolsRegexRoute
  '/tools/timestamp': typeof ToolsTimestampRoute
  '/tools/url-codec': typeof ToolsUrlCodecRoute
  '/tools/uuid': typeof ToolsUuidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/base64'
    | '/tools/beverage'
    | '/tools/case'
    | '/tools/color'
    | '/tools/cron'
    | '/tools/hash'
    | '/tools/json'
    | '/tools/mock-data'
    | '/tools/redact'
    | '/tools/regex'
    | '/tools/timestamp'
    | '/tools/url-codec'
    | '/tools/uuid'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/base64'
    | '/tools/beverage'
    | '/tools/case'
    | '/tools/color'
    | '/tools/cron'
    | '/tools/hash'
    | '/tools/json'
    | '/tools/mock-data'
    | '/tools/redact'
    | '/tools/regex'
    | '/tools/timestamp'
    | '/tools/url-codec'
    | '/tools/uuid'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/tools/base64'
    | '/tools/beverage'
    | '/tools/case'
    | '/tools/color'
    | '/tools/cron'
    | '/tools/hash'
    | '/tools/json'
    | '/tools/mock-data'
    | '/tools/redact'
    | '/tools/regex'
    | '/tools/timestamp'
    | '/tools/url-codec'
    | '/tools/uuid'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsBeverageRoute: typeof ToolsBeverageRoute
  ToolsCaseRoute: typeof ToolsCaseRoute
  ToolsColorRoute: typeof ToolsColorRoute
  ToolsCronRoute: typeof ToolsCronRoute
  ToolsHashRoute: typeof ToolsHashRoute
  ToolsJsonRoute: typeof ToolsJsonRoute
  ToolsMockDataRoute: typeof ToolsMockDataRoute
  ToolsRedactRoute: typeof ToolsRedactRoute
  ToolsRegexRoute: typeof ToolsRegexRoute
  ToolsTimestampRoute: typeof ToolsTimestampRoute
  ToolsUrlCodecRoute: typeof ToolsUrlCodecRoute
  ToolsUuidRoute: typeof ToolsUuidRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/uuid': {
      id: '/tools/uuid'
      path: '/tools/uuid'
      fullPath: '/tools/uuid'
      preLoaderRoute: typeof ToolsUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/url-codec': {
      id: '/tools/url-codec'
      path: '/tools/url-codec'
      fullPath: '/tools/url-codec'
      preLoaderRoute: typeof ToolsUrlCodecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/timestamp': {
      id: '/tools/timestamp'
      path: '/tools/timestamp'
      fullPath: '/tools/timestamp'
      preLoaderRoute: typeof ToolsTimestampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/regex': {
      id: '/tools/regex'
      path: '/tools/regex'
      fullPath: '/tools/regex'
      preLoaderRoute: typeof ToolsRegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/redact': {
      id: '/tools/redact'
      path: '/tools/redact'
      fullPath: '/tools/redact'
      preLoaderRoute: typeof ToolsRedactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/mock-data': {
      id: '/tools/mock-data'
      path: '/tools/mock-data'
      fullPath: '/tools/mock-data'
      preLoaderRoute: typeof ToolsMockDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json': {
      id: '/tools/json'
      path: '/tools/json'
      fullPath: '/tools/json'
      preLoaderRoute: typeof ToolsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hash': {
      id: '/tools/hash'
      path: '/tools/hash'
      fullPath: '/tools/hash'
      preLoaderRoute: typeof ToolsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cron': {
      id: '/tools/cron'
      path: '/tools/cron'
      fullPath: '/tools/cron'
      preLoaderRoute: typeof ToolsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color': {
      id: '/tools/color'
      path: '/tools/color'
      fullPath: '/tools/color'
      preLoaderRoute: typeof ToolsColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/case': {
      id: '/tools/case'
      path: '/tools/case'
      fullPath: '/tools/case'
      preLoaderRoute: typeof ToolsCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/beverage': {
      id: '/tools/beverage'
      path: '/tools/beverage'
      fullPath: '/tools/beverage'
      preLoaderRoute: typeof ToolsBeverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/tools/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsBeverageRoute: ToolsBeverageRoute,
  ToolsCaseRoute: ToolsCaseRoute,
  ToolsColorRoute: ToolsColorRoute,
  ToolsCronRoute: ToolsCronRoute,
  ToolsHashRoute: ToolsHashRoute,
  ToolsJsonRoute: ToolsJsonRoute,
  ToolsMockDataRoute: ToolsMockDataRoute,
  ToolsRedactRoute: ToolsRedactRoute,
  ToolsRegexRoute: ToolsRegexRoute,
  ToolsTimestampRoute: ToolsTimestampRoute,
  ToolsUrlCodecRoute: ToolsUrlCodecRoute,
  ToolsUuidRoute: ToolsUuidRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
